### ISSUE TITLE
Exporter configuration via Helm Chart doesn't sync crdsToDiscover and overwriteCrdsActions options

### ISSUE THREAD

**Issue by irizzant** [port-labs/port-k8s-exporter#86]
I have deployed Exporter with Helm chart version 0.2.36 in kubernetes 1.30 with the following helm chart configuration:
```yaml
overwriteConfigurationOnRestart: true
eventListener:
  type: POLLING
configMap:
  name: config-k8s.yaml
  config:
    crdsToDiscover: ".metadata.ownerReferences[0].kind == \"CompositeResourceDefinition\" and .spec.scope == \"Namespaced\""
    overwriteCrdsActions: false
    resources:
    - kind: v1/namespaces
    .... # omitted for brevity
```
In Port this configuration translates into:
```yaml
resources:
    - kind: v1/namespaces
    .... # omitted for brevity
```

The Kubernetes ConfigMap contains the right configuration, but it's not mirrored in Port though.

This is a problem because if I manually update the kubernetes datasource in Port adding the missing configurations:
```yaml
crdsToDiscover: ".metadata.ownerReferences[0].kind == \"CompositeResourceDefinition\" and .spec.scope == \"Namespaced\""
    overwriteCrdsActions: false
```
then at the next restart of the exporter pod the configuration is lost.
On the other end, by setting `overwriteConfigurationOnRestart: true`  I loose the possibility to keep the configuration in sync with Port
